name: Build docker image

on: [push]

jobs:
    build-action:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # Not all for time waste reasons
                platform: ["linux/amd64", "linux/arm64"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install docker buildx
              uses: docker/setup-buildx-action@v1
              with:
                buildx-version: latest
                qemu-version: latest
            - name: Build action image
              run: PLATFORM="${{ matrix.platform }}" make docker-build
