name: Build docker image

on: [push]

jobs:
    build-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: install docker buildx
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                version: latest
            - name: Build action image
              run: make docker-build
