name: Install notary
on:
  push:

jobs:
  sign-manifest:
    name: Sign the docker hub manifest
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-go@v2
          with:
            go-version: '^1.12'
        - name: 'Install module'
          run: |
            export GO111MODULE=on
            go get github.com/theupdateframework/notary
            go install -tags pkcs11 github.com/theupdateframework/notary/cmd/notary@latest
            notary --help
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
            password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        - name: Notary list
          run: NOTARY_AUTH="$(printf "${{ secrets.DOCKER_REPOSITORY_LOGIN }}:${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | base64 -w0)" notary list docker.io/botsudo/nut-upsd -s https://notary.docker.io
