name: Publish Docker image
on:
  push:
    tags:
       - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        max-parallel: 1
        matrix:
            platform: ["linux/arm64", "linux/amd64", "linux/ppc64le", "linux/arm/v7", "linux/arm/v6"]
    steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
            password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        - name: Install docker buildx
          uses: crazy-max/ghaction-docker-buildx@v1
          with:
            version: latest
        - name: Build action image
          run: PLATFORM="${{ matrix.platform }}" IMAGE_TAG="docker.io/botsudo/nut-upsd:latest" make docker-build
          env:
            DOCKER_BUILDKIT: 1

        - name: Sign and push docker image
          uses: sudo-bot/action-docker-sign@latest
          with:
            image-ref: "docker.io/botsudo/nut-upsd:latest"
            private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
            private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
            private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
