name: Publish Docker image
on:
  push:
    tags:
       - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
            include:
                # All non supported by base image are commented
                - { platform: "linux/arm64", platform-tag: "arm64" }
                - { platform: "linux/amd64", platform-tag: "amd64" }
                - { platform: "linux/arm/v7", platform-tag: "armv7" }
                - { platform: "linux/arm/v6", platform-tag: "armv6" }
                - { platform: "linux/ppc64le", platform-tag: "ppc64le" }
                #- { platform: "linux/riscv64", platform-tag: "riscv64" }
                - { platform: "linux/s390x", platform-tag: "s390x" }
                - { platform: "linux/386", platform-tag: "386" }
                #- { platform: "linux/mips64le", platform-tag: "mips64le" }
                #- { platform: "linux/mips64", platform-tag: "mips64" }

    steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
            password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        # https://github.com/docker/setup-qemu-action
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-buildx-action
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build action image
          run: PLATFORM="${{ matrix.platform }}" IMAGE_TAG="docker.io/botsudo/nut-upsd:${{ matrix.platform-tag }}-latest" make docker-build
          env:
            DOCKER_BUILDKIT: 1

        - name: Sign and push docker image
          uses: sudo-bot/action-docker-sign@latest
          with:
            image-ref: "docker.io/botsudo/nut-upsd:${{ matrix.platform-tag }}-latest"
            private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
            private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
            private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}

  sign-manifest:
    name: Sign the docker hub manifest
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
            password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        - name: Notary list
          run: NOTARY_AUTH="$(printf "${{ secrets.DOCKER_REPOSITORY_LOGIN }}:${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | base64 -w0)" notary list docker.io/botsudo/nut-upsd -s https://notary.docker.io
